sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: i1BFq1wao5gKZTlcwpC6Ao7uMZmGXBiTN4HSHamxF5oALhG2mOdETAqEawfX2GdLxj34YPki5uYn6W8YorCQWYWVnh2V0rJGGnXwpU/XzUV/tBTvo102xwhTlav5gE4g103HxKdOaUoGKGYl4rh6ZtzE6eT+R1PUb0ynPMxfwTgEyhn/ziLmtgDlyCQTNqAAOEJlKmeBs77Jnx3WfWwuZNJaoMZBUOy7smOQR7hSFWsVrQnz7cbieEbaIzCNf59KeRSGy0QtJBw0Gex0pNppD2aW+MMCac/p06IwAwmF/tauHGgZwWV7p9S+EbRJCsKReq37uIs9LAF9orSfdegvHkSMZu2ezufMP7LaeLtKq0l/3xOWXuHOQ8ASf2hvQhxQUbP72l77a2hGmshqrFv242lTF6bmYfU90f7GXwJorPLT3ieDj2dXlX9XBendCEjkS9pFJ9WQ/7YTts1nRaaT9a0WP1vaAfcMeo6cKJlV7ZsO34cEhIRnLi/QLgOpRiv+Scd41VodNqS9JL7cOGbevwjqNjoUYlk+BAES0HgpnvKztxlnZBLPcbrbGmhJQbf3sEWGnpalesxlSAZT4GvhgyyYJUyZ7WGvnVuSafIa3I3Svc1PpMw80GobOFjCQg0TFaphKwEwzpW1eFiXn0aGiZpwpDAAUshIoigutg6GPjw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Poor-Clare_2548
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy